#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void disco()

{

system("color 6B");
system("pause");
system("color 6C");
system("pause");
system("color 6D");
system("pause");
system("color 6E");
system("pause");
system("color 6F");
system("pause");
system("color 70");
system("pause");
system("color 71");
system("pause");
system("color 72");
system("pause");
system("color 73");
system("pause");
system("color 74");
system("pause");
system("color 75");
system("pause");
system("color 76");
system("pause");
system("color 77");
system("pause");
system("color 78");
system("pause");
system("color 79");
system("pause");
system("color 7A");
system("pause");
system("color 7B");
system("pause");
system("color 7C");
system("pause");
system("color 7D");
system("pause");
system("color 7E");
system("pause");
system("color 7F");
system("pause");
system("color 80");
system("pause");
system("color 81");
system("pause");
system("color 82");
system("pause");
system("color 83");
system("pause");
system("color 84");
system("pause");
system("color 85");
system("pause");
system("color 86");
system("pause");
system("color 87");
system("pause");
system("color 88");
system("pause");
system("color 89");
system("pause");
system("color 8A");
system("pause");
system("color 8B");
system("pause");
system("color 8C");
system("pause");
system("color 8D");
system("pause");
system("color 8E");
system("pause");
system("color 8F");
system("pause");
system("color 90");
system("pause");
system("color 91");
system("pause");
system("color 92");
system("pause");
system("color 93");
system("pause");
system("color 94");
system("pause");
system("color 95");
system("pause");
system("color 96");
system("pause");
system("color 97");
system("pause");
system("color 98");
system("pause");
system("color 99");
system("pause");
system("color 9A");
system("pause");
system("color 9B");
system("pause");
system("color 9C");
system("pause");
system("color 9D");
system("pause");
system("color 9E");
system("pause");
system("color 9F");
system("pause");
system("color A0");
system("pause");
system("color A1");
system("pause");
system("color A2");
system("pause");
system("color A3");
system("pause");
system("color A4");
system("pause");
system("color A5");
system("pause");
system("color A6");
system("pause");
system("color A7");
system("pause");
system("color A8");
system("pause");
system("color A9");
system("pause");
system("color AA");
system("pause");
system("color AB");
system("pause");
system("color AC");
system("pause");
system("color AD");
system("pause");
system("color AE");
system("pause");
system("color AF");
system("pause");
system("color B0");
system("pause");
system("color B1");
system("pause");
system("color B2");
system("pause");
system("color B3");
system("pause");
system("color B4");
system("pause");
system("color B5");
system("pause");
system("color B6");
system("pause");
system("color B7");
system("pause");
system("color B8");
system("pause");
system("color B9");
system("pause");
system("color BA");
system("pause");
system("color BB");
system("pause");
system("color BC");
system("pause");
system("color BD");
system("pause");
system("color BE");
system("pause");
system("color BF");
system("pause");
system("color C0");
system("pause");
system("color C1");
system("pause");
system("color C2");
system("pause");
system("color C3");
system("pause");
system("color C4");
system("pause");
system("color C5");
system("pause");
system("color C6");
system("pause");
system("color C7");
system("pause");
system("color C8");
system("pause");
system("color C9");
system("pause");
system("color CA");
system("pause");
system("color CB");
system("pause");
system("color CC");
system("pause");
system("color CD");
system("pause");
system("color CE");
system("pause");
system("color CF");
system("pause");
system("color D0");
system("pause");
system("color D1");
system("pause");
system("color D2");
system("pause");
system("color D3");
system("pause");
system("color D4");
system("pause");
system("color D5");
system("pause");
system("color D6");
system("pause");
system("color D7");
system("pause");
system("color D8");
system("pause");
system("color D9");
system("pause");
system("color DA");
system("pause");
system("color DB");
system("pause");
system("color DC");
system("pause");
system("color DD");
system("pause");
system("color DE");
system("pause");
system("color DF");
system("pause");
system("color E0");
system("pause");
system("color E1");
system("pause");
system("color E2");
system("pause");
system("color E3");
system("pause");
system("color E4");
system("pause");
system("color E5");
system("pause");
system("color E6");
system("pause");
system("color E7");
system("pause");
system("color E8");
system("pause");
system("color E9");
system("pause");
system("color EA");
system("pause");
system("color EB");
system("pause");
system("color EC");
system("pause");
system("color ED");
system("pause");
system("color EE");
system("pause");
system("color EF");
system("pause");
system("color F0");
system("pause");
system("color F1");
system("pause");
system("color F2");
system("pause");
system("color F3");
system("pause");
system("color F4");
system("pause");
system("color F5");
system("pause");
system("color F6");
system("pause");
system("color F7");
system("pause");
system("color F8");
system("pause");
system("color F9");
system("pause");
system("color FA");
system("pause");
system("color FB");
system("pause");
system("color FC");
system("pause");
system("color FD");
system("pause");
system("color FE");
system("pause");
system("color FF");
system("pause");
}
/*
W = 87 || 119
S = 83 || 115
A = 65 || 97
D = 68 || 100
Q = 81 || 113
0 = Black
1 = Blue
2 = Green
3 = Aqua
4 = Red
5 = Purple
6 = Yellow
7 = White
8 = Gray
9 = Light Blue
A = Light Green
B = Light Aqua
C = Light Red
D = Light Purple
E = Light Yellow
F = Bright White
*/
